#!/bin/bash
# Skript kontrollib käsurealt antud täisarvu paarsust.

if [ $# -ne 1 ]
then
    echo "Kasutamine: ./paarsus täisarv"
    exit 1
fi

arv=$1

if [ $((arv % 2)) -eq 0 ]
then
    echo "Antud arv on paaris"
else
    echo "Antud arv on paaritu"
fi
